server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: vago-service-user

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vago.user.model.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      vago:
        mapper: debug
        service: info
        controller: info

# SpringDoc / Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

vago:
  jwt:
    secret-key: ${vago.jwt.secret-key}
    access-token-ttl: ${vago.jwt.access-token-ttl}
    refresh-token-ttl: ${vago.jwt.refresh-token-ttl}
    token-name: ${vago.jwt.token-name}
